site_name: Dextool Docs
site_url: https://haliliceylan.github.io/Dextool-Docs
repo_url: https://github.com/haliliceylan/Dextool-Docs
theme:
  name: material
nav:
  - Installation: index.md
  - Config Options: config-options.md
  - Apply Mutation Testing: apply-mutation-testing.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
