site_name: Dextool Docs
site_url: https://haliliceylan.github.io/Dextool-Docs
repo_url: https://github.com/haliliceylan/Dextool-Docs
theme:
  name: material
nav:
  - Installation: index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences